Repository arkflow-rs/arkflow, pull requests merged in 2025-04, with the labels that each got.

#189 doc: add k8s doc
  .github/workflows/docker.yml
  .github/workflows/rust.yml
  docker/Dockerfile
  docs/docs/deploy/k8s/deployment.md
Labels: documentation

#220 docs: release v0.2.0
  docs/blog/2024/04/13-v0.2.0-release.md
  docs/docs/components/0-inputs/generate.md
  docs/docs/components/0-inputs/http.md
  docs/docs/components/0-inputs/kafka.md
  docs/docs/components/1-buffers/memory.md
  docs/docs/components/2-processors/json.md
  docs/docs/components/2-processors/protobuf.md
  docs/docs/components/3-outputs/http.md
  docs/docs/components/3-outputs/kafka.md
  docs/docs/components/3-outputs/mqtt.md
  docs/docs/deploy/_category_.json
  docs/docs/deploy/k8s-deployment.md
  examples/kafka_example.yaml
Labels: documentation

#273 feat: add experimental vector vrl support
  Cargo.lock
  Cargo.toml
  crates/arkflow-core/src/lib.rs
  crates/arkflow-plugin/Cargo.toml
  crates/arkflow-plugin/src/processor/json.rs
  crates/arkflow-plugin/src/processor/mod.rs
  crates/arkflow-plugin/src/processor/vrl.rs
  examples/vrl_example.yaml
Labels: enhancement

#281 fix: Dockerfile
  docker/Dockerfile
Labels: bug
